version: '3.8' # vs mais atual

services:
  app:
    build: ./
    container_name: idevcoder.com
    restart: always
    tty: true
    working_dir: /idevcoder.com
    volumes:
      - ./app/:/idevcoder.com
    # ports:
    #   - "3000:3000"
    networks:
      - idevcoder-network
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - idevcoder-network
    depends_on:
      - app

networks:
  idevcoder-network:
    driver: host
